class LayoutOptimizer:
  def __init__(
    self,
    nodes: list[list[str]],
    edges: list[list[tuple[str, str, int]]],
  ): ...
  def swap_nodes(self, layer_index: int, max_iterations: int, temperature: float) -> None: ...
  def cooldown(self, layer_index: int, max_iterations: int, start_temp: float, end_temp: float, steps: int) -> None: ...
  def get_nodes(self) -> tuple[list[str], list[str]]: ...
  def count_crossings(self) -> int: ...
