from typing import List, Tuple

class LayoutOptimizer:
  def __init__(
    self,
    nodes_left: List[str],
    nodes_right: List[str],
    edges: List[Tuple[str, str, int]],
  ): ...
  def swap_nodes_left(self, max_iterations: int, temperature: float) -> None: ...
  def swap_nodes_right(self, max_iterations: int, temperature: float) -> None: ...
  def get_nodes(self) -> Tuple[List[str], List[str]]: ...
  def count_crossings(self) -> int: ...
